services:
  migrate:
    environment: &profile
      PE_AGENT_DEPLOY_PROFILE: platform-shadow
      PE_AGENT_ENVIRONMENT: production
      PE_AGENT_PLATFORM_PROFILE: platform
      PE_AGENT_DECISION_PROFILE: typesafe
      PE_AGENT_ARCHIVE_ENABLED: "false"
  api:
    environment: *profile
  worker:
    environment: *profile
